import { BuildBadge } from '../components/build-badge.tsx';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}<BuildBadge /></body>
    </html>
  )
}
